name: Dynamic Variables Workflow

on:
  workflow_dispatch:
    inputs:
      git_repo_name:
        description: "Enter the repo name"
        required: true
        type: string
      app_type:
        description: "Enter the name app type"
        required: true
        type: choice
        options:
          - CAP
          - UI5
env:
  NAME: "Amar"
  AGE: "38"
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Set Dynamic Variable
        id: set_variable
        run: |
          if [ "${{ github.event.inputs.app_type }}" == "UI5" ]; then
            echo "SONAR_PROJECT=${{  github.event.inputs.git_repo_name }}-corprateit" >> $GITHUB_ENV
            echo "SONAR_SOURCES=." >> $GITHUB_ENV
            echo "SONAR_EXCLUSIONS=webapp/test/**,webapp/css/**.json" >> $GITHUB_ENV
            echo "FORTIFY_APPLICATIONID=AID331-${{  github.event.inputs.git_repo_name }}" >> $GITHUB_ENV
            echo "FORTIFY_FILESPECIFIER=srv/**/.ts" >> $GITHUB_ENV
          else
            echo "SONAR_PROJECT=cap.${{  github.event.inputs.git_repo_name }}" >> $GITHUB_ENV
            echo "SONAR_SOURCES=." >> $GITHUB_ENV
            echo "SONAR_EXCLUSIONS=test/**" >> $GITHUB_ENV
            echo "FORTIFY_APPLICATIONID=AID331-${{  github.event.inputs.git_repo_name }}" >> $GITHUB_ENV
            echo "FORTIFY_FILESPECIFIER=srv/**/.ts" >> $GITHUB_ENV
          fi

      - name: "create sonar-project.properties"
        run: |
          echo "sonar.projectKey=$SONAR_PROJECT" >> sonar-project.properties
          echo "sonar.ProjectVersion=$SONAR_PROJECT" >> sonar-project.properties
          echo "sonar.sources=." >> sonar-project.properties
          
          cat sonar-project.properties
      - name: "create fortify.confgig.yml"
        run: |
          echo "applicationID=$FORTIFY_APPLICATIONID" >> fortify.config.yml
          echo "fileSpecifier=$FORTIFY_FILESPECIFIER" >> fortify.config.yml
          cat fortify.config.yml
      
